// web/src/common/components/ui/ThemeToggle.vue
<script setup lang="ts">
import { useTheme } from '../../composables/useTheme'
import { Sun, Moon } from 'lucide-vue-next'

const { toggle } = useTheme()
</script>

<template>
  <button
    class="relative w-9 h-9 flex items-center justify-center rounded-md bg-card border border-border hover:bg-primary/10 transition"
    @click="toggle"
  >
    <Sun class="absolute h-5 w-5 transition-all sun-icon" />
    <Moon class="absolute h-5 w-5 transition-all moon-icon" />
  </button>
</template>

// web/src/app/shared/components/theme-toggle/theme-toggle.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Sun, Moon } from 'lucide-angular';
import { ThemeService } from '../../../core/services/theme-service';

@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './theme-toggle.component.html',
  styleUrl: './theme-toggle.component.css',
})
export class ThemeToggleComponent {
  readonly icons = { Sun, Moon };

  constructor(public themeService: ThemeService) {}

  toggle(): void {
    this.themeService.toggle();
  }
}

<button
  type="button"
  aria-label="Toggle theme"
  (click)="toggle()"
  class="relative flex h-9 w-9 items-center justify-center rounded-md
         text-muted-foreground hover:text-foreground
         hover:bg-secondary transition-colors"
>
  <!-- Sun -->
  <lucide-icon
    [img]="icons.Sun"
    class="h-5 w-5 absolute transition-all
           rotate-0 scale-100 dark:-rotate-90 dark:scale-0"
  />

  <!-- Moon -->
  <lucide-icon
    [img]="icons.Moon"
    class="h-5 w-5 absolute transition-all
           rotate-90 scale-0 dark:rotate-0 dark:scale-100"
  />
</button>
